// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDl4oVKPT2H1mjRfv-wKj6n-Y3Xi9tU5Ac',
    appId: '1:863815135687:web:501066bddf25fe4b85a9e2',
    messagingSenderId: '863815135687',
    projectId: 'volunred',
    authDomain: 'volunred.firebaseapp.com',
    storageBucket: 'volunred.appspot.com',
    measurementId: 'G-0M67PS0HYG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGE8rDiYSBOxDBhmvvEpGLO3Q2IHixd48',
    appId: '1:863815135687:android:36cdb7dbb53ed62a85a9e2',
    messagingSenderId: '863815135687',
    projectId: 'volunred',
    storageBucket: 'volunred.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJOZhXzImH4H8vCPSEfhTihgYYubrMK6w',
    appId: '1:863815135687:ios:26fb839ca842002985a9e2',
    messagingSenderId: '863815135687',
    projectId: 'volunred',
    storageBucket: 'volunred.appspot.com',
    iosBundleId: 'com.example.volunredApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJOZhXzImH4H8vCPSEfhTihgYYubrMK6w',
    appId: '1:863815135687:ios:26fb839ca842002985a9e2',
    messagingSenderId: '863815135687',
    projectId: 'volunred',
    storageBucket: 'volunred.appspot.com',
    iosBundleId: 'com.example.volunredApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDl4oVKPT2H1mjRfv-wKj6n-Y3Xi9tU5Ac',
    appId: '1:863815135687:web:f71f6e0416e5048085a9e2',
    messagingSenderId: '863815135687',
    projectId: 'volunred',
    authDomain: 'volunred.firebaseapp.com',
    storageBucket: 'volunred.appspot.com',
    measurementId: 'G-43TM6WD5WN',
  );
}
